### ISSUE TITLE
Support for Storybook 8

### ISSUE THREAD

**Issue by yunyongEthan** [SHO-ai-org/addon-stitches#10]
First of all, thank you for developing the addon that makes it easy to apply the stitches theme.

I'm configuring Storybook using the multiple-themes-stitches addon.
I recently upgraded to Storybook version 8.0.0 and proceeded with the migration.
However, I noticed that the peerDependencies you're referring to are configured to only support version 7 of Storybook. 
(Since it still works fine with Storybook 8, it seems that there shouldn't be a need for significant changes.)

Here's the warning I'm encountering
```bash
➤ YN0060: │ @storybook/blocks is listed by your project with version 8.0.0, which doesn't satisfy what multiple-themes-stitches (pd162b) requests (^7.0.0-rc.1).
➤ YN0060: │ @storybook/components is listed by your project with version 8.0.0, which doesn't satisfy what multiple-themes-stitches (p5b6e8) requests (^7.0.0-rc.1).
➤ YN0060: │ @storybook/core-events is listed by your project with version 8.0.0, which doesn't satisfy what multiple-themes-stitches (pda755) requests (^7.0.0-rc.1).
➤ YN0060: │ @storybook/manager-api is listed by your project with version 8.0.0, which doesn't satisfy what multiple-themes-stitches (pc00fb) requests (^7.0.0-rc.1).
➤ YN0060: │ @storybook/preview-api is listed by your project with version 8.0.0, which doesn't satisfy what multiple-themes-stitches (p6fc29) requests (^7.0.0-rc.1).
➤ YN0060: │ @storybook/theming is listed by your project with version 8.0.0, which doesn't satisfy what multiple-themes-stitches (pcffe4) requests (^7.0.0-rc.1).
➤ YN0060: │ @storybook/types is listed by your project with version 8.0.0, which doesn't satisfy what multiple-themes-stitches (p2d1dd) requests (^7.0.0-rc.1).
```

Note: Your peerDependencies
```bash
    "@storybook/blocks": ^7.0.0-rc.1
    "@storybook/components": ^7.0.0-rc.1
    "@storybook/core-events": ^7.0.0-rc.1
    "@storybook/manager-api": ^7.0.0-rc.1
    "@storybook/preview-api": ^7.0.0-rc.1
    "@storybook/theming": ^7.0.0-rc.1
    "@storybook/types": ^7.0.0-rc.1
```

**Comment by yunyongEthan** [comment]
Additionally, I'm receiving the following warnings in the console due to the deprecation of Icons from @storybook/components.

Use of the deprecated Icons (paintbrush) component detected. Please use the @storybook/icons component directly. For more informations, see the migration notes at https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#icons-is-deprecated

**Comment by mathisobadia** [comment]
@yunyongEthan It took a while because the release process was a bit broken but we just release a new version (2.0.3) with the right dependency upgrade. Let me know if it works for you !

**Comment by yunyongEthan** [comment]
@mathisobadia I applied the new version and it works well without errors.
thanks :)
